version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      LOGSPOUT: ignore
    volumes:
    # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - data:/usr/share/elasticsearch/data
    networks:
      - honeydock
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    container_name: logstash
    environment:
      LOGSPOUT: ignore
    volumes:
    # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/patterns/:/usr/share/logstash/patterns/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - honeydock
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    environment:
      LOGSPOUT: ignore
    # volumes:
    # - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - honeydock
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  data:
    driver: local

networks:
  honeydock:
    driver: bridge
